map_update_interval: 1.0
maxUrange: 3.5
sigma: 0.05
kernelSize: 3.5
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 0
minimumScore: 100
srr: 0.8
srt: 1.0
str: 1.0
stt: 0.8
linearUpdate: 0.1
angularUpdate: 0.1
temporalUpdate: 0.5
resampleThreshold: 0.5
particles: 50
xmin: -3.5
ymin: -3.5
xmax: 3.5
ymax: 3.5
delta: 0.05
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005